### ISSUE TITLE
[BUG] SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by misterpyrrhuloxia** [vlc-rpc/vlc-discord-rpc#5]
Getting this as of the last day or two:
```powershell
C:\Users\Spiff>cd "C:\Users\Spiff\Documents\Scripts\vlc-discord-rich-presence"

C:\Users\Spiff\Documents\Scripts\vlc-discord-rich-presence>npm i

up to date, audited 23 packages in 365ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Users\Spiff\Documents\Scripts\vlc-discord-rich-presence>node .
Connecting to Discord...
(node:40796) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Logged in as Spiff
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new VLCStatus (C:\Users\Spiff\Documents\Scripts\vlc-discord-rich-presence\node_modules\vlc.js\lib\src\http\classes\VLCStatus.js:13:27)
    at C:\Users\Spiff\Documents\Scripts\vlc-discord-rich-presence\node_modules\vlc.js\lib\src\http\Requester.js:65:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.2.0

C:\Users\Spiff\Documents\Scripts\vlc-discord-rich-presence>
```

**Comment by Lauren1066** [comment]
I'm unable to reproduce this issue. I am late to this, but if you could provide any more information it would be appreciated. Everything seems to work on my end.

**Comment by Lauren1066** [comment]
Closing due to inactivity and I believe whatever issue it was is likely fixed.
