### ISSUE TITLE
Error in request: Failed to reach VLC: 401 Unauthorized

### ISSUE THREAD

**Issue by nielot0330** [vlc-rpc/vlc-discord-rpc#52]
Error in request: Failed to reach VLC: 401 Unauthorized
Failed to fetch VLC status: Error: Failed to reach VLC. Is it open?
    at Client.request (file:///C:/Users/nielot/Desktop/vlc-discord-rpc-main/Functions/VLC_Client.js:45:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.getStatus (file:///C:/Users/nielot/Desktop/vlc-discord-rpc-main/Functions/VLC_Client.js:19:20)
    at async diff (file:///C:/Users/nielot/Desktop/vlc-discord-rpc-main/Functions/status.js:27:20)

**Comment by Lauren1066** [comment]
Hello,
Are you using detached or the regular mode?

**Comment by Lauren1066** [comment]
Did you change any config values? I will do some testing.

**Comment by Lauren1066** [comment]
Hello,
After some digging it seems the password must be set. I will update the documentation, apologies.

In you `config.js` please set the password field. From the testing on my end, it seems you should not have to set it the VLC preferences.

**Comment by Lauren1066** [comment]
I found the issue and with the commit https://github.com/vlc-rpc/vlc-discord-rpc/commit/21679248c574af218e3743b1342cffcb63866fc0 you should not need the password anymore.
